### ISSUE TITLE
Undefined type "byte" in main.c

### ISSUE THREAD

**Issue by aCube1** [FelipeVieira4/WolfEngine#1]
In this [line](https://github.com/FelipeVieira4/WolfEngine/blob/d45df1d4fa9668c64de4b35a99fa0002e71e417f/src/main.c#L55):
```c
  byte informap=MAP[y][x];
```

Undefined type `byte`, please use `uint8_t` provided by `stdint.h`.

**Comment by Fibertero** [comment]
Nice

**Comment by aCube1** [comment]
@FelipeVieira4 I think I can resolve this issue, this is simple, I can do it

**Comment by FelipeVieira4** [comment]
Thanks you i will fix this
